// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Decision struct {
	ID                string  `json:"id"`
	TicketID          string  `json:"ticketId"`
	Action            string  `json:"action"`
	Confidence        float64 `json:"confidence"`
	Reasoning         string  `json:"reasoning"`
	OverriddenByHuman bool    `json:"overriddenByHuman"`
	CreatedAt         string  `json:"createdAt"`
}

type Mutation struct {
}

type Query struct {
}

type Ticket struct {
	ID        string `json:"id"`
	CreatedAt string `json:"createdAt"`
	Subject   string `json:"subject"`
	Body      string `json:"body"`
	Status    string `json:"status"`
	Category  string `json:"category"`
	Urgency   string `json:"urgency"`
	RiskScore int    `json:"riskScore"`
	UpdatedAt string `json:"updatedAt"`
}
